-- LINK RRSS persistent memory layer
-- Keeps social content/history independent from short-lived Zernio snapshots.

create table if not exists public.link_rrss_posts (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references public.link_rrss_accounts(id) on delete cascade,
  external_post_id text not null,
  platform_post_id text,
  status text,
  media_type text,
  content text,
  thumbnail_url text,
  post_url text,
  published_at timestamptz,
  scheduled_for timestamptz,
  metrics jsonb not null default '{}'::jsonb,
  raw jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(account_id, external_post_id)
);

create index if not exists link_rrss_posts_account_published_idx
  on public.link_rrss_posts(account_id,published_at desc);

create table if not exists public.link_rrss_post_metric_history (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.link_rrss_posts(id) on delete cascade,
  observed_on date not null default current_date,
  observed_at timestamptz not null default now(),
  metrics jsonb not null default '{}'::jsonb,
  unique(post_id,observed_on)
);

create table if not exists public.link_rrss_conversations (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references public.link_rrss_accounts(id) on delete cascade,
  external_conversation_id text not null,
  participant_id text,
  participant_name text,
  participant_username text,
  participant_picture text,
  platform_url text,
  status text,
  unread_count integer not null default 0,
  last_message text,
  last_message_at timestamptz,
  raw jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(account_id,external_conversation_id)
);

create table if not exists public.link_rrss_account_memory (
  account_id uuid primary key references public.link_rrss_accounts(id) on delete cascade,
  post_count integer not null default 0,
  conversation_count integer not null default 0,
  earliest_post_at timestamptz,
  latest_post_at timestamptz,
  last_successful_sync_at timestamptz,
  history_backfilled_at timestamptz,
  history_status text not null default 'pending',
  updated_at timestamptz not null default now()
);

alter table public.link_rrss_posts enable row level security;
alter table public.link_rrss_post_metric_history enable row level security;
alter table public.link_rrss_conversations enable row level security;
alter table public.link_rrss_account_memory enable row level security;

drop policy if exists "link members read rrss posts" on public.link_rrss_posts;
create policy "link members read rrss posts" on public.link_rrss_posts
for select to authenticated using (public.link_world_is_member());

drop policy if exists "link members write rrss posts" on public.link_rrss_posts;
create policy "link members write rrss posts" on public.link_rrss_posts
for all to authenticated using (public.link_world_is_member()) with check (public.link_world_is_member());

drop policy if exists "link members read rrss metric history" on public.link_rrss_post_metric_history;
create policy "link members read rrss metric history" on public.link_rrss_post_metric_history
for select to authenticated using (public.link_world_is_member());

drop policy if exists "link members write rrss metric history" on public.link_rrss_post_metric_history;
create policy "link members write rrss metric history" on public.link_rrss_post_metric_history
for all to authenticated using (public.link_world_is_member()) with check (public.link_world_is_member());

drop policy if exists "link members read rrss conversations memory" on public.link_rrss_conversations;
create policy "link members read rrss conversations memory" on public.link_rrss_conversations
for select to authenticated using (public.link_world_is_member());

drop policy if exists "link members write rrss conversations memory" on public.link_rrss_conversations;
create policy "link members write rrss conversations memory" on public.link_rrss_conversations
for all to authenticated using (public.link_world_is_member()) with check (public.link_world_is_member());

drop policy if exists "link members read rrss account memory" on public.link_rrss_account_memory;
create policy "link members read rrss account memory" on public.link_rrss_account_memory
for select to authenticated using (public.link_world_is_member());

drop policy if exists "link members write rrss account memory" on public.link_rrss_account_memory;
create policy "link members write rrss account memory" on public.link_rrss_account_memory
for all to authenticated using (public.link_world_is_member()) with check (public.link_world_is_member());

create or replace view public.link_rrss_public_posts_v as
select
  p.id,pr.business_id,a.source_id,p.account_id,a.platform,a.username,
  p.external_post_id,p.platform_post_id,p.status,p.media_type,p.content,
  p.thumbnail_url,p.post_url,p.published_at,p.scheduled_for,p.metrics,
  p.first_seen_at,p.last_seen_at,p.updated_at
from public.link_rrss_posts p
join public.link_rrss_accounts a on a.id=p.account_id
join public.link_rrss_sources s on s.id=a.source_id
join public.link_rrss_profiles pr on pr.id=s.profile_id;

create or replace view public.link_rrss_public_memory_v as
select
  m.account_id,pr.business_id,a.source_id,a.platform,a.username,
  m.post_count,m.earliest_post_at,m.latest_post_at,m.last_successful_sync_at,
  m.history_backfilled_at,m.history_status,m.updated_at
from public.link_rrss_account_memory m
join public.link_rrss_accounts a on a.id=m.account_id
join public.link_rrss_sources s on s.id=a.source_id
join public.link_rrss_profiles pr on pr.id=s.profile_id;

grant select on public.link_rrss_public_posts_v to anon, authenticated;
grant select on public.link_rrss_public_memory_v to anon, authenticated;
